apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: Subhadeep
type: Opaque
stringData:
  MONGODB_URI: mongodb://shopuser:ShopNowPass123@mongo-0.mongo-headless.Subhadeep.svc.cluster.local:27017/shopnow?authSource=admin